import Image from "next/image";
import Link from "next/link";
import { content, partnerPath, type Locale } from "./content";
import { Header } from "./Header";
import { CapabilityCard, CTA, Footer, ProcessFlow, SectionHeading, FeatureIcon } from "./Sections";
import { Leaf, Recycle, Factory, Waves } from "lucide-react";
import { DataVisual } from "./Visuals";
export function Hero({ locale }: { locale: Locale }) {
 const t = content[locale];
 const benefits = locale === "de" ? ["Geringere Umweltbelastung", "Ressourcenrückgewinnung", "Praxisnahe Industrielösungen", "Kreislauforientierte Prozesse"] : ["Lower environmental impact", "Resource recovery", "Practical industrial solutions", "Circular process thinking"];
 const icons = [Leaf, Recycle, Factory, Waves];
 return <><section className="hero photo-hero" id="top"><div className="section-shell hero-grid"><div className="hero-copy"><p className="eyebrow">Intelligent Water Solutions</p><h1>{t.headline}</h1><p className="hero-intro">{t.intro}</p><div className="hero-actions"><Link href="#services" className="button">{t.explore}<span aria-hidden="true">↗</span></Link><Link href="#contact" className="text-link hero-secondary">{t.discuss}<span aria-hidden="true">→</span></Link></div><p className="focus-line">{t.focus}</p></div><figure className="hero-photograph"><Image src="/images/amir-talebi-founder-2026.png" alt={locale === "de" ? "Textilveredelungsanlage mit industriellen Maschinen und Rohrleitungen" : "Textile finishing facility with industrial machinery and pipework"} fill sizes="(max-width: 767px) 100vw, 60vw" priority/><svg className="hero-water-overlay" viewBox="0 0 600 700" preserveAspectRatio="none" aria-hidden="true"><path d="M0 0h95C-30 270 185 500 600 700H0Z" fill="white" fillOpacity=".88"/><path d="M0 440C180 575 370 540 600 680v20C320 680 190 590 0 545Z" fill="#00A9B7" fillOpacity=".28"/><path d="M0 535C190 610 400 600 600 700H0Z" fill="#026CB0" fillOpacity=".3"/></svg><figcaption>{locale === "de" ? "Textilveredelung · Branchenkontext" : "Textile finishing · Industry context"}<a href="https://unsplash.com/photos/industrial-textile-factory-with-machinery-and-pipes-HpPmiduLDC0" target="_blank" rel="noreferrer">{locale === "de" ? "Foto" : "Photo"}: Lalit Kumar / Unsplash</a></figcaption></figure></div></section><section className="value-strip" aria-label={locale === "de" ? "Unser Fokus" : "Our focus"}><div className="section-shell"><ul>{benefits.map((text,i)=>{const Icon=icons[i];return <li key={text}><Icon aria-hidden="true" strokeWidth={1.5}/><span>{text}</span></li>;})}</ul></div></section></>;
}
export function Home({ locale }: { locale: Locale }) {
 const t = content[locale];
 const schema = {"@context":"https://schema.org","@type":"Organization",name:"HydroTex",url:"https://www.hydrotex.eu",logo:"https://www.hydrotex.eu/images/brand/hydrotex-logo-horizontal.png",email:"contact@hydrotex.eu",founder:{"@type":"Person",name:"Dr.-Ing. Amir Talebi",sameAs:"https://de.linkedin.com/in/amirtalebienvtech"}};
 return <><Header locale={locale}/><main id="main" className="homepage" lang={locale}><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><Hero locale={locale}/>
  <section className="section soft-section" id="services"><div className="section-shell"><SectionHeading label={t.approachLabel} title={t.approach}/><div className="capabilities">{t.stages.map(([title,text],index)=><CapabilityCard key={title} index={index} title={title} text={text}/>)}</div></div></section>
  <section className="section" id="technology"><div className="section-shell two-columns technology-grid"><div><SectionHeading label={t.technologyLabel} title={t.technology}/><p className="body-copy">{t.technologyCopy}</p><ul className="theme-list">{t.themes.map(theme=><li key={theme}>{theme}</li>)}</ul><p className="technical-note">{t.criteria}</p><Link className="text-link" href={partnerPath(locale)+"#roadmap"}>{t.technicalLink}<span aria-hidden="true">→</span></Link></div><ProcessFlow locale={locale}/></div></section>
  <section className="section soft-section" id="impact"><div className="section-shell"><SectionHeading label="Intelligent Water Solutions" title={t.why}/><div className="pillars">{t.pillars.map(([title,text],i)=><article key={title}><FeatureIcon index={i}/><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
  <section className="section intelligence-section" id="intelligence"><div className="section-shell two-columns intelligence-grid"><div><SectionHeading label={t.intelligenceLabel} title={t.intelligence}/><p className="body-copy">{t.intelligenceCopy}</p></div><DataVisual locale={locale}/></div></section>
  <section className="section international-section" id="pathway"><div className="section-shell"><SectionHeading label={t.internationalLabel} title={t.international}/><p className="body-copy limited-copy">{t.internationalNote}</p><div className="international-columns"><article><div className="country-heading"><h3>{t.germany}</h3><span className="german-line" aria-hidden="true"/></div><ul>{t.germanyItems.map(item=><li key={item}>{item}</li>)}</ul></article><article><h3>{t.internationalSide}</h3><ul>{t.internationalItems.map(item=><li key={item}>{item}</li>)}</ul></article></div></div></section>
  <section className="section soft-section" id="partnerships-status"><div className="section-shell"><div className="heading-with-link"><SectionHeading label={t.partnersLabel} title={t.partnersTitle}/><Link className="text-link" href={partnerPath(locale)}>{t.partnersLink}<span aria-hidden="true">→</span></Link></div><div className="partner-grid">{t.partners.map(([title,text])=><article key={title}><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
  <section className="formation-section soft-section" id="company-formation" aria-labelledby="formation-label"><div className="section-shell"><p className="eyebrow" id="formation-label">{locale === "de" ? "UNTERNEHMENSAUFBAU & NACHWEISE" : "COMPANY FORMATION & DOCUMENTATION"}</p><div className="formation-grid"><article><h3>{locale === "de" ? "Gründung in Deutschland" : "Formation in Germany"}</h3><p className="body-copy">{locale === "de" ? "Die Gründung der HydroTex UG (haftungsbeschränkt) ist derzeit in Vorbereitung." : "The establishment of HydroTex UG (limited liability) is currently in preparation."}</p></article><article><h3>{locale === "de" ? "IHK-Tragfähigkeitsbewertung" : "IHK Viability Assessment"}</h3><p className="body-copy">{locale === "de" ? "Das Gründungsvorhaben HydroTex wurde im Rahmen der IHK-Tragfähigkeitsprüfung positiv bewertet. Die entsprechende Stellungnahme wird von der IHK auf Anfrage direkt an zuständige öffentliche Stellen übermittelt." : "The HydroTex founding concept received a positive viability assessment from the IHK. The corresponding IHK statement is provided directly to requesting public authorities."}</p></article></div></div></section>
  <section className="founder-section soft-section" id="founder"><div className="section-shell"><div className="founder-grid"><Image src="/images/amir-talebi-founder-2026.png" alt="Dr.-Ing. Amir Talebi, Founder of HydroTex" width={320} height={360} sizes="(max-width: 600px) 160px, 240px" unoptimized className="founder-portrait"/><div><p className="eyebrow">{t.founderRole}</p><h2>Dr.-Ing. Amir Talebi</h2><p className="body-copy">{t.founderCopy}</p><a className="text-link" href="https://de.linkedin.com/in/amirtalebienvtech" target="_blank" rel="noreferrer">{t.founderLink}<span aria-hidden="true">↗</span><span className="sr-only"> (LinkedIn)</span></a></div></div></div></section>
  <CTA locale={locale}/></main><Footer locale={locale}/></>;
}
